- name: "Checkout GitHub Action"
  uses: actions/checkout@main

- name: "Docker Acr Authentication and Image Building"
  uses: azure/docker-login@v1
  with:
    login-server: mnitacr.azurecr.io
    username: ${{ secrets.ACR_USERNAME }}
    password: ${{ secrets.ACR_PASSWORD }}

- run: |
    docker build . -t mnitacr.azurecr.io/angular:latest
    docker push mnitacr.azurecr.io/angular:latest
- name: "Login via Azure CLI"
  uses: azure/login@v1
  with:
    creds: ${{ secrets.AZURE_CREDENTIALS }}

- name: "Image Deployment to Azure Web App For Containers"
  uses: azure/webapps-deploy@v2
  with:
    app-name: "AngularMnitPOC"
    images: "mnitacr.azurecr.io/angular:latest"

- name: Azure logout
  run: |
    az logout
